apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: from-rest-to-grpc

build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    # for the Golang demo
    # - image: qaware/grpc-beer-client
    #   context: grpc-beer-client/
    # - image: qaware/rest-beer-golang
    #   context: rest-beer-golang/
    # - image: qaware/rest-beer-service
    #   context: rest-beer-service/
    # - image: qaware/grpc-beer-service
    #   context: grpc-beer-service/
    
    # for the Quarkus demo
    - image: qaware/quarkus-beer-rest
      context: quarkus-beer-rest/
      docker:
        dockerfile: quarkus-beer-rest/src/main/docker/Dockerfile.jvm
    - image: qaware/quarkus-beer-grpc
      context: quarkus-beer-grpc/
      docker:
        dockerfile: quarkus-beer-grpc/src/main/docker/Dockerfile.jvm
    
    # for the Micronaut demo
    - image: qaware/micronaut-beer-rest
      context: micronaut-beer-rest/
      jib:
        type: gradle
    - image: qaware/micronaut-beer-grpc
      context: micronaut-beer-grpc/
      jib:
        type: gradle

    # for gRPC ecosystem demo
    - image: qaware/grpc-beer-gateway
      context: grpc-beer-gateway/
    - image: qaware/grpc-beer-nginx
      context: grpc-beer-nginx/
    - image: qaware/grpc-beer-envoy
      context: grpc-beer-envoy/
  local:
    # push: false
    useBuildkit: true
    useDockerCLI: false

deploy:
  kubectl:
    manifests: 
      # for the Golang demo
      # - rest-beer-golang/k8s/*.yaml
      # - rest-beer-service/k8s/*.yaml
      # - grpc-beer-client/k8s/*.yaml
      # - grpc-beer-service/k8s/*.yaml

      # for the Quarkus demo
      # - quarkus-beer-rest/k8s/*.yaml
      # - quarkus-beer-grpc/k8s/*.yaml

      # for the Micronaut demo
      - micronaut-beer-rest/k8s/*.yaml
      - micronaut-beer-grpc/k8s/*.yaml

      - grpc-beer-envoy/k8s/*.yaml
      - grpc-beer-gateway/k8s/*.yaml
      - grpc-beer-nginx/k8s/*.yaml
      - grpc-beer-ui/k8s/*.yaml
      
portForward:
  # for the Golang demo
  # - resourceName: rest-beer-golang
  #   resourceType: service
  #   namespace: default
  #   port: 8080
  #   localPort: 18080
  # - resourceName: rest-beer-service
  #   resourceType: service
  #   namespace: default
  #   port: 8081
  #   localPort: 18081
  # - resourceName: grpc-beer-service
  #   resourceType: service
  #   namespace: default
  #   port: 9090
  #   localPort: 19090
  
  # for the Quarkus demo
  - resourceName: rest-beer-service
    resourceType: service
    namespace: default
    port: 8080
    localPort: 18080
  - resourceName: grpc-beer-service
    resourceType: service
    namespace: default
    port: 9090
    localPort: 19090

  - resourceName: grpc-beer-gateway
    resourceType: service
    namespace: default
    port: 8090
    localPort: 18090
  - resourceName: grpc-beer-envoy
    resourceType: service
    namespace: default
    port: 8091
    localPort: 18091
  - resourceName: grpc-beer-nginx
    resourceType: service
    namespace: default
    port: 8888
    localPort: 18888
  - resourceName: grpc-beer-ui
    resourceType: service
    namespace: default
    port: 6969
    localPort: 16969