apiVersion: v1
kind: Service
metadata:
  name: rest-beer-golang
spec:
  selector:
    app: rest-beer-golang
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8081
      targetPort: http
